### ISSUE TITLE
Statistiekjes-pagina

### ISSUE THREAD

**Issue by FMJansen** [Opwiekanikstemmen-nl/website#2]
- genderbalans: wat is de verhouding mannen vs. vrouwen?
- leeftijd: 18-25, 25-23, ... hoeveel zitten er in welke categorie?
- 1946-1964: hoe groot aandeel hebben de boomers? (silent >1945, gen x 1965-1980, millenials 1980-1995, gen z 1996+)
- stedelijk/landelijk: wat is de verhouding tussen het aantal meest stedelijke kandidaten en het aantal meest landelijke kandidaten?
- welke woonplaats meeste kandidaten?
- hoeveel mensen buiten Nederland?
- hoeveel mensen komen er van onder de rivieren? Zeeland, Friesland, Limburg, Waddeneilanden
- eerdere politieke functies (politieke ervaring): hoeveel hebben er al een raadsfunctie op zitten?
- grootte partijen: wie heeft de meeste en minste kandidaten?
- meer <CEO’s die Pieter heten> dan <vrouwelijke CEO’s> (lekker filters combineren tot je iets leuks hebt gevonden)

**Comment by roberrrt-s** [comment]
kaartje bouwen dus!

**Comment by FMJansen** [comment]
[Eerste versie](https://tweedekamer2023.opwiekanikstemmen.nl/cijfers) gemaakt met 4ab9d4c81796fa13771f002c98f66ef2a29f35d7

Leeftijd weten we helaas nog niet, geslachten missen we nog veel maar kunnen we wel iets, stedelijk/landelijk hebben we de data maar ben te incapabel om dat toe te passen ( @toonmeijer ik snap niet hoe ik van woonplaats naar stedelijkheidsgraag kan ) en politieke ervaring moeten we nog binnenhalen.
